before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential devscripts debhelper quilt pkg-config
script:
  - cd jake-1.0 && debuild -us -uc
deploy:
  provider: packagecloud
  username: roidrage
  repository: testy
  skip_cleanup: true
  token:
    secure: J8D7AgZAFtrwKop0/bUWZqKW5APwEbzWRu8FYY7nMTsCJiM/YodTVW0p3mkc4xxIqSorUh4VbOUI3/yV7aYonz4DHMZHKS+iWuTlrQYIo/C33EVakG44RdEgGWrnUx7n3RKN8FaZ+vuyf9JMwCvFBneUpfS67YjCVdFZZmNWtY0=
  dist: ubuntu/precise
  on:
    branch: master
