before_install:
- sudo apt-get update -qq
- sudo apt-get install -y build-essential devscripts debhelper quilt pkg-config
script:
- sh build.sh
deploy:
  provider: packagecloud
  username: roidrage
  edge: true
  repository: testy
  skip_cleanup: true
  token:
    secure: M+dWt53MUJsaOyy6tJUILat0rM/aKr7wXpfgNFIgi60Q/7dmFa0C9ocfOCOBgTFpQ+9/h3UjwSTgU971b/wwmoLw+swahSfAqw1Awv6gDHXAzb04d9jOTccZzg276eh3muznKqiZlNy3+oVX/m2bJ5NFrPLcV8N+Vj0BmiFXliI=
  dist: ubuntu/precise
  on:
    branch: master
