.\" Manpage for jake
.TH man 1 "17 May 2014" "1.0" "jake man page"
.SH NAME
jake \- let the world know about my friend jake
.SH SYNOPSIS
jake
.SH DESCRIPTION
jake is a binary executable program for letting users learn about my good friend Jake.
.SH OPTIONS
jake does not take any options
.SH SEE ALSO
nice(1), yes(1)
.SH BUGS
No known bugs (because Jake is awesome).
.SH AUTHOR
Joe Damato (joe@packagecloud.io).
